GameUi/Areas/Game/Controllers/BasesController.cs
using SpaceTraffic.GameUi.Controllers;
/**
Copyright 2010 FAV ZCU

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

**/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpaceTraffic.GameUi.Extensions;
using SpaceTraffic.Entities;

namespace SpaceTraffic.GameUi.Areas.Game.Controllers
{
	[Authorize]
	public class BasesController : AbstractController
	{
		//
		// GET: /Bases/
				
		public ActionResult Index()
		{
			var partialView = PartialView();
			partialView.ViewBag.bases = GSClient.GameService.GetAllBases();
			return partialView;
		}

		//
		// GET: /Bases/Info
		public PartialViewResult Info(string planetName)
		{
			var partialView = PartialView("_Info");
			partialView = addHeaderViewBag(partialView, planetName);
			partialView.ViewBag.trader = GSClient.CargoService.GetTraderAtBase(partialView.ViewBag.currentBase.BaseId);
			return partialView;
		}

		

		//
		// GET: /Bases/Ships
		public PartialViewResult Ships(string planetName)
		{
			var partialView = PartialView("_Ships");
			partialView = addHeaderViewBag(partialView, planetName);
			partialView.ViewBag.ships = GSClient.PlayerService.GetPlayersShipsAtBase(getCurrentPlayerId(), partialView.ViewBag.currentBase.BaseId);
			return partialView;
		}

		//
		// GET: /Bases/ShipDetail
		public ActionResult ShipDetail(int shipId)
		{
			if (!GSClient.PlayerService.PlayerHasSpaceShip(getCurrentPlayerId(), shipId))
			{
				return new EmptyResult().Error("Tato loď ti nepatří!");
			}
			var partialView = PartialView("_ShipDetail");
			SpaceShip ship = GSClient.ShipsService.GetDetailedSpaceShip(shipId);
			partialView.ViewBag.ship = ship;

			return partialView;
		}

		//
		// GET: /Bases/Goods
		public PartialViewResult Goods(string planetName)
		{
			var partialView = PartialView("_Goods");
			partialView = addHeaderViewBag(partialView, planetName);
			if (partialView.ViewBag.currentBase != null)
			{
				partialView.ViewBag.trader = GSClient.CargoService.GetTraderAtBaseWithCargo(partialView.ViewBag.currentBase.BaseId);
			}
			return partialView;
		}


		/// <summary>
		/// Creates parameters for header partial view
		/// Full planet name (location) = "StarSystem.Name\Planet.Name"
		/// </summary>
		/// <param name="partialView">Partial view to modify.</param>
		/// <param name="planetName">Name of the planet.</param>
		/// <returns></returns>
		private PartialViewResult addHeaderViewBag(PartialViewResult partialView, string planetName)
		{
			var currentBase = GSClient.GameService.GetBaseByName(getCurrentStarSystem() + "\\" + planetName);
			partialView.ViewBag.currentBase = currentBase;
			partialView.ViewBag.planetName = planetName;
			return partialView;
		}

	}
}

GameUi/Areas/Game/Controllers/ShipsController.cs
/**
Copyright 2010 FAV ZCU

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

**/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpaceTraffic.GameUi.Models.Ui;
using SpaceTraffic.GameUi.Areas.Game.Models;
using System.Xml.Linq;
using SpaceTraffic.Entities;
using SpaceTraffic.GameUi.Extensions;
using SpaceTraffic.GameUi.Controllers;

namespace SpaceTraffic.GameUi.Areas.Game.Controllers
{

	[Authorize]
	public class ShipsController : AbstractController
	{

		const int MAX_DAMAGE = 100;

		public PartialViewResult Index() {
			return ShipList();
		}
		
		//
		// GET: /Ships/BuyModel		
		/// <summary>
		/// Buys the ship of specified model
		/// </summary>
		/// <returns></returns>
		public ActionResult BuyModel(int baseId, string starSystemName, string model)
		{
			ActionResult result = new EmptyResult();
			ShipModel shipModel = getAllShips().Where(shipType => shipType.Model == model).First();
			if (shipModel != null){
				if (GSClient.PlayerService.PlayerHasEnaughCredits(getCurrentPlayerId(), shipModel.Price))
				{
					GSClient.GameService.PerformAction(getCurrentPlayerId(), "ShipBuy", getCurrentPlayerId(), starSystemName, baseId, shipModel.FuelCapacity, shipModel.FuelCapacity, shipModel.Model, shipModel.Model, shipModel.Price, shipModel.Consumption, shipModel.WearRate, shipModel.MaxSpeed, shipModel.CarryingCapacity, shipModel.CssClass, shipModel.Image);
				} else {
					return result.Warning(String.Format("Nemáš dostatek kreditů na koupi lodě {0}.", shipModel.Model));
				}
			}else{
				return result.Error("Tento typ lodi neexistuje.");
			}
			return result.Success(String.Format("Loď typu {0} byla úspěšně zakoupena.", shipModel.Model));
		}


		public PartialViewResult ShipList()
		{
			// získání lodí uživatele
			IList<SpaceShip> ships = GSClient.PlayerService.GetPlayersShips(getCurrentPlayerId());

			var viewResult = PartialView("_ShipList");
			viewResult.ViewBag.Ships = ships;
			return viewResult;
		}

		public ActionResult ShipCargo(int shipId)
		{
			if (!GSClient.PlayerService.PlayerHasSpaceShip(getCurrentPlayerId(), shipId))
			{
				return new EmptyResult().Error("Tato loď ti nepatří!");
			}
			var partialView = PartialView("_ShipCargo");
			SpaceShip ship = GSClient.ShipsService.GetDetailedSpaceShip(shipId);
			partialView.ViewBag.ship = ship;

			return partialView;
		}
		
		

		public PartialViewResult BuyShip(int baseId)
		{
			// získání všech dostupných modelů lodí
			List<ShipModel> ships = getAllShips();

			var viewResult = PartialView("_BuyShip");
			viewResult.ViewBag.Ships = ships;
			viewResult.ViewBag.baseId = baseId;
			viewResult.ViewBag.starSystemName = getCurrentStarSystem();
			return viewResult;
		}

		//
		// GET: /Ships/Refuel
		public ActionResult Refuel(int shipId, int baseId)
		{
			int curPlayerId = getCurrentPlayerId();
			
			var partialView = PartialView("_ShipRefuel");
			int credits = GSClient.PlayerService.GetPlayersCredits(curPlayerId);

			SpaceShip ship = GSClient.ShipsService.GetSpaceShip(shipId);
			partialView.ViewBag.ship = ship;
			if(!controlShipAccess(ship)){
				return new EmptyResult().Error(this.ErrorMessage);
			}

			
			Trader trader = GSClient.CargoService.GetTraderAtBase(baseId);
			partialView.ViewBag.trader = trader;

			partialView.ViewBag.maxToBuy = Math.Min(ship.FuelTank - ship.CurrentFuelTank, credits / trader.FuelPrice);
			return partialView;
		}

		[HttpPost]
		public ActionResult Refuel(FuelBuyModel values, int shipId, int baseId)
		{
			int curPlayerId = getCurrentPlayerId();
			int credits = GSClient.PlayerService.GetPlayersCredits(curPlayerId);
			SpaceShip ship = GSClient.ShipsService.GetSpaceShip(shipId);
			if (!controlShipAccess(ship))
			{
				return new EmptyResult().Error(this.ErrorMessage);
			}

			Trader trader = GSClient.CargoService.GetTraderAtBase(baseId);
			int maxAmount = Math.Min(ship.FuelTank - ship.CurrentFuelTank, credits / trader.FuelPrice);
			int finalAmount = Math.Min(maxAmount, values.Amount);
			if (finalAmount > 0)
			{
				string[] planetString = trader.Base.Planet.Split('\\');
				GSClient.GameService.PerformAction(curPlayerId, "ShipRefuel", planetString[0], planetString[1], shipId, finalAmount, trader.FuelPrice);

				return new EmptyResult().Success("Tankuje se " + finalAmount + " jednotek paliva.");
			}
			else {
				return new EmptyResult().Warning("Nádrž lodi je plná.");
			}
		}


		//
		// GET: /Ships/Repair
		public ActionResult Repair(int shipId, int baseId)
		{
			int curPlayerId = getCurrentPlayerId();
			var partialView = PartialView("_ShipRepair");
			int credits = GSClient.PlayerService.GetPlayersCredits(curPlayerId);

			SpaceShip ship = GSClient.ShipsService.GetSpaceShip(shipId);
			partialView.ViewBag.ship = ship;
			if (!controlShipAccess(ship))
			{
				return new EmptyResult().Error(this.ErrorMessage);
			}


			Trader trader = GSClient.CargoService.GetTraderAtBase(baseId);
			partialView.ViewBag.trader = trader;

			partialView.ViewBag.maxToRepair = Math.Min(ship.DamagePercent, credits / trader.RepairPrice);
			return partialView;
		}

		[HttpPost]
		public ActionResult Repair(RepairShipModel values, int shipId, int baseId)
		{
			int curPlayerId = getCurrentPlayerId();
			
			int credits = GSClient.PlayerService.GetPlayersCredits(curPlayerId);
			SpaceShip ship = GSClient.ShipsService.GetSpaceShip(shipId);

			if (!controlShipAccess(ship))
			{
				return new EmptyResult().Error(this.ErrorMessage);
			}

			Trader trader = GSClient.CargoService.GetTraderAtBase(baseId);
			int maxAmount = Math.Min((int)ship.DamagePercent, credits / trader.RepairPrice);
			int finalAmount = Math.Min(maxAmount, values.Amount);
			if (finalAmount > 0)
			{
				string[] planetString = trader.Base.Planet.Split('\\');
				GSClient.GameService.PerformAction(curPlayerId, "ShipRepair", planetString[0], planetString[1], shipId, finalAmount, trader.RepairPrice);

				return new EmptyResult().Success("Opravuje se " + finalAmount + " procent poškození.");
			}
			else {
				return new EmptyResult().Warning("Loď není poškozená.");
			}
		}
		

		/// <summary>
		/// Returns the list of all ships defined in SpaceShips.xml
		/// </summary>
		/// <returns>List of ship models with parameters from xml.</returns>
		private List<ShipModel> getAllShips()
		{
			List<ShipModel> ships = new List<ShipModel>();

			XDocument shipsXML = this.loadXmlAssembly("Ship", "SpaceShips");//getting XML

			var shipsQuery = from shipsNode in shipsXML.Descendants("ships").Descendants("ship")
							 select shipsNode;// getting ship node in ships XML

			foreach (XElement shipNode in shipsQuery) {
				ShipModel ship = new ShipModel();

				ship.Model = (string)shipNode.Descendants("model").FirstOrDefault();
				ship.Manufacturer = (string)shipNode.Descendants("manufacturer").FirstOrDefault();
				ship.Power = (int)shipNode.Descendants("power").FirstOrDefault();
				ship.Consumption = (double)shipNode.Descendants("consumption").FirstOrDefault();
				ship.WearRate = (double)shipNode.Descendants("wearRate").FirstOrDefault();
				ship.FuelCapacity = (int)shipNode.Descendants("fuelCapacity").FirstOrDefault();
				ship.CarryingCapacity = (int)shipNode.Descendants("carryingCapacity").FirstOrDefault();
				ship.Image = (string)shipNode.Descendants("image").FirstOrDefault();
				ship.Price = (int)shipNode.Descendants("price").FirstOrDefault();
				ship.Description = (string)shipNode.Descendants("description").FirstOrDefault();
				ship.MaxSpeed = (int)shipNode.Descendants("maxSpeed").FirstOrDefault();
				ship.CssClass = (string)shipNode.Descendants("cssClass").FirstOrDefault();

				ships.Add(ship);
			}
			return ships;
		}

	}
}

GameUi/Areas/Game/Views/Bases/Index.cshtml
<h1>Základny</h1>
<div class="basesList scrollable">
	@{
	foreach (var planetBase in @ViewBag.bases)
	{
		<div href="" data-starsystem="@planetBase.StarSystemName" class="falseLink baseLink">
			<a href="@Url.Action("Info", "Bases", new { planetName = planetBase.PlanetName })" class="ajax originalLink" data-related-element-id="contextPanelContent"></a>
				<span class="icon basesIcon hugeIcon"></span>
				<p class="baseInfo">
					<strong class="baseName">@planetBase.BaseName</strong>
					<span class="starSystemName">@planetBase.StarSystemName</span>
				</p>
		</div>
			}
			<div style="clear:both;"></div>
			}
</div>
<script>
	$('.basesList .falseLink').click(function (e) {
		$.cookie("currentStarSystem", $(this).data('starsystem'), { path: '/' });
		StarSystemLoader.switchToStarSystem($(this).data('starsystem'));
		ajaxClick(e, $(this).find('.originalLink'));
	});

</script>

GameUi/Areas/Game/Views/Bases/_Goods.cshtml
@Html.Partial("_Header")

<a href="@Url.Action("Goods", "Bases", new { planetName = ViewBag.planetName })" class="ajax refreshButton" data-related-element-id="contextPanelContent">↻</a>
<div class="scrollable">
@{
	if (ViewBag.trader != null)
	{
		foreach(var traderCargo in ViewBag.trader.TraderCargos){
			@Html.Partial("../Cargo/CargoCards/_CargoCardBasic", new ViewDataDictionary { { "cargo", traderCargo }, { "fromBase", true }})
		}
	}
}
</div>
<script>
	$('#contextPanel .contextBtn').removeClass('active');
	$('#planetGoods').addClass('active');
</script>

GameUi/Areas/Game/Views/Bases/_Header.cshtml
@if (ViewBag.currentBase != null)
{ 
<h2>@ViewBag.currentBase.BaseName</h2>
}
@if (ViewBag.planetName != null)
{
<a href="@Url.Action("Info", "Bases", new { planetName = ViewBag.planetName })" id="planetInfo" class="ajax btn btn-info contextBtn" data-related-element-id="contextPanelContent">Souhrn</a>
<a href="@Url.Action("Ships", "Bases", new { planetName = ViewBag.planetName })" id="planetShips" class="ajax btn btn-ships contextBtn" data-related-element-id="contextPanelContent">Lodě</a>
<a href="@Url.Action("Goods", "Bases", new { planetName = ViewBag.planetName })" id="planetGoods" class="ajax btn btn-credits contextBtn" data-related-element-id="contextPanelContent">Zboží</a>
}

GameUi/Areas/Game/Views/Bases/_Info.cshtml
@Html.Partial("_Header")

<a href="@Url.Action("Info", "Bases", new { planetName = ViewBag.planetName })" class="ajax refreshButton" data-related-element-id="contextPanelContent">↻</a>
<div class="infoPanel">
    <div class="economicLevel">
        <h5>Úroveň vyspělosti</h5>
        <span>
            <strong class="value">@ViewBag.trader.EconomicLevel</strong>
        </span>
    </div>
    <div style="clear: both;"></div>
    <div class="fuelPrice">
		<h5>Cena paliva</h5>
		<span>
			<strong class="value">@ViewBag.trader.FuelPrice</strong>
			<span class="icon creditsIcon largeIcon"></span>
		</span>
	</div>
	<div class="repairPrice">
		<h5>Cena oprav</h5>
		<span>
			<strong class="value">@ViewBag.trader.RepairPrice</strong>
			<span class="icon creditsIcon largeIcon"></span>
		</span>
	</div>
	<div style="clear: both;"></div>
</div>
<script>
	$('#contextPanel .contextBtn').removeClass('active');
	$('#planetInfo').addClass('active');
</script>

GameUi/Areas/Game/Views/Bases/_ShipDetail.cshtml
@Html.Partial("_Header")

<a href="@Url.Action("ShipDetail", "Bases", new { shipId = ViewBag.ship.SpaceShipId })" class="ajax refreshButton" data-related-element-id="contextPanelContent">↻</a>


@Html.Partial("../Ships/ShipCards/_ShipCardDetailed", new ViewDataDictionary { { "ship", ViewBag.ship }, { "index", 0 }, {"shipUI", true} })


<div id="spaceShipDetailContent"></div>

GameUi/Areas/Game/Views/Bases/_Ships.cshtml
@Html.Partial("_Header")

<a href="@Url.Action("Ships", "Bases", new { planetName = ViewBag.planetName })" class="ajax refreshButton" data-related-element-id="contextPanelContent">↻</a>
<div>
@if (ViewBag.currentBase != null)
{
	<a href="@Url.Action("BuyShip", "Ships", new { baseId = ViewBag.currentBase.BaseId })" class="ajax btn btn-ships" data-related-element-id="mainPanelContent">Koupit loď</a>
}
</div>

<div class="scrollable">
	@{
		int i = 0;
		foreach (var ship in @ViewBag.Ships)
		{
			i++;
			<a href="@Url.Action("ShipDetail", "Bases", new { shipId = @ship.SpaceShipId })" class="ajax" data-related-element-id="contextPanelContent">
				@Html.Partial("../Ships/ShipCards/_ShipCardBasic", new ViewDataDictionary { { "ship", ship }, { "index", i } })
			</a>
		}
		if (i == 0)
		{
			<p class="infoNote">
				Na této základně nemáte žádné lodě.
			</p>
		}
	}

</div>
<script>
	$('#contextPanel .contextBtn').removeClass('active');
	$('#planetShips').addClass('active');
</script>